### ISSUE TITLE
ConnectionPoolException with Dart SDK V1.17

### ISSUE THREAD

**Issue by zijam** [luizmineo/connection_pool#1]
After updating to Dart SDK V1.17, I get ConnectionPoolException when I try to start my app.

```
Unhandled exception:
ConnectionPoolException: Failed to open connection. Cause: type '_SinkTransformerStreamSubscription<List<int>, MongoReplyMessage>' is not a subtype of type 'StreamSubscription<List<int>>' of 'value' where
  _SinkTransformerStreamSubscription is from dart:async
  MongoReplyMessage is from package:mongo_dart/mongo_dart.dart
  List is from dart:core
  int is from dart:core
  MongoReplyMessage is from package:mongo_dart/mongo_dart.dart
  StreamSubscription is from dart:async
  List is from dart:core
  int is from dart:core

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:938)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sestegra** [comment]
I'm using Dart SDK 1.18 without any error.

Do you still get the exception ?
If yes, could you check mongo_dart version that you're using.

**Comment by zijam** [comment]
the interface StreamSubscription has changed in V1.17, the bug was fixed by a patch from dart team to MongoDB packages.
